import Head from 'next/head';
import Image from 'next/image';
import styles from './home.module.css';
import {
	Navbar,
	Nav,
	NavDropdown,
	Container,
	Form,
	FormControl,
	Button,
} from 'react-bootstrap';

export default function Home() {
	return (
		<>
			<Navbar bg='light' expand='lg'>
				<Container fluid>
					<Navbar.Brand href='#'>Navbar scroll</Navbar.Brand>
					<Navbar.Toggle aria-controls='navbarScroll' />
					<Navbar.Collapse id='navbarScroll'>
						<Nav
							className='me-auto my-2 my-lg-0'
							style={{ maxHeight: '100px' }}
							navbarScroll
						>
							<Nav.Link href='#action1'>Home</Nav.Link>
							<Nav.Link href='#action2'>Link</Nav.Link>
							<NavDropdown
								title='Link'
								id='navbarScrollingDropdown'
							>
								<NavDropdown.Item href='#action3'>
									Action
								</NavDropdown.Item>
								<NavDropdown.Item href='#action4'>
									Another action
								</NavDropdown.Item>
								<NavDropdown.Divider />
								<NavDropdown.Item href='#action5'>
									Something else here
								</NavDropdown.Item>
							</NavDropdown>
							<Nav.Link href='#' disabled>
								Link
							</Nav.Link>
						</Nav>
						<Form className='d-flex'>
							<FormControl
								type='search'
								placeholder='Search'
								className='me-2'
								aria-label='Search'
							/>
							<Button variant='outline-success'>Search</Button>
						</Form>
					</Navbar.Collapse>
				</Container>
			</Navbar>
			<div className={styles.container}>
				<Head>
					<title>Create Next App</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<main className={styles.main}>
					<h1 className={styles.title}>
						Welcome to <a href='https://nextjs.org'>Next.js!</a>
					</h1>

					<p className={styles.description}>
						Get started by editing{' '}
						<code className={styles.code}>pages/index.js</code>
					</p>

					<div className={styles.grid}>
						<a
							href='https://nextjs.org/docs'
							className={styles.card}
						>
							<h2>Documentation &rarr;</h2>
							<p>
								Find in-depth information about Next.js features
								and API.
							</p>
						</a>

						<a
							href='https://nextjs.org/learn'
							className={styles.card}
						>
							<h2>Learn &rarr;</h2>
							<p>
								Learn about Next.js in an interactive course
								with quizzes!
							</p>
						</a>

						<a
							href='https://github.com/vercel/next.js/tree/master/examples'
							className={styles.card}
						>
							<h2>Examples &rarr;</h2>
							<p>
								Discover and deploy boilerplate example Next.js
								projects.
							</p>
						</a>

						<a
							href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
							className={styles.card}
						>
							<h2>Deploy &rarr;</h2>
							<p>
								Instantly deploy your Next.js site to a public
								URL with Vercel.
							</p>
						</a>
					</div>
				</main>

				<footer className={styles.footer}>
					<a
						href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
						target='_blank'
						rel='noopener noreferrer'
					>
						Powered by{' '}
						<span className={styles.logo}>
							<Image
								src='/static/images/vercel.svg'
								alt='Vercel Logo'
								width={72}
								height={16}
							/>
						</span>
					</a>
				</footer>
			</div>
		</>
	);
}
