import Head from 'next/head';
import Image from 'next/image';
import styles from './home.module.css';

import NavBar from 'components/layout/navbar';

export default function Home() {
	return (
		<>
			<div className={styles.container}>
				<Head>
					<title>Who's at the Hackathon?</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<link rel='icon' href='/favicon.ico' />
				</Head>

				<main className={styles.main}>
					<h1 className={styles.title}>
						Who's at the Hackathon 2021?
					</h1>

					<p className={styles.description}>Hackathon Rules</p>

					<div className={styles.grid}>
						<a href='javascript:void(0)' className={styles.card}>
							<h2>Ideas... &rarr;</h2>
							<ul>
								<li>NextJS Headless CMS</li>
								<li>NextJS tooling/admin screens</li>
								<li>NextJS scaffolding/tooling</li>
								<li>etc...</li>
							</ul>
						</a>

						<a
							href='https://nextjs.org/learn'
							className={styles.card}
						>
							<h2>Strictly NextJS &rarr;</h2>
							<p>
								Learn about Next.js in an interactive course
								with quizzes!
							</p>
						</a>

						<a href='javascript:void(0)' className={styles.card}>
							<h2>+ve Points &rarr;</h2>
							<ul>
								<li>A finished project</li>
								<li>Code - Problem Corelation</li>
								<li>Quality of code</li>
								<li>Architecture</li>
							</ul>
						</a>

						<a href='javascript:void(0)' className={styles.card}>
							<h2>-ve Points &rarr;</h2>
							<ul>
								<li>Unfinished And/Or Errors</li>
								<li>Incomplete documentation</li>
								<li>Can't build</li>
								<li>Can't See</li>
							</ul>
						</a>
					</div>
				</main>
			</div>
		</>
	);
}
